"""Initial migration

Revision ID: 9197469d6634
Revises: 5f056e7833e0
Create Date: 2024-06-04 07:39:01.772448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9197469d6634'
down_revision: Union[str, None] = '5f056e7833e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart_items', sa.Column('total_cost', sa.DECIMAL(), sa.Computed('quantity * (select price from products where id = product_id)', persisted=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cart_items', 'total_cost')
    # ### end Alembic commands ###
