"""Initial migration

Revision ID: ca9570e0b1b9
Revises: 5fd8c05c16fe
Create Date: 2024-06-16 15:23:59.376361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca9570e0b1b9'
down_revision: Union[str, None] = '5fd8c05c16fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
