"""Initial migration

Revision ID: e5180896e64b
Revises: 30865af12972
Create Date: 2024-06-10 14:07:14.104896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5180896e64b'
down_revision: Union[str, None] = '30865af12972'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('carts', 'total_price',
               existing_type=sa.INTEGER(),
               type_=sa.DECIMAL(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('carts', 'total_price',
               existing_type=sa.DECIMAL(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
